---
title: "wgcna"
author: "Ryan Sheridan"
date: "2023-06-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r "chunk opts", echo = FALSE}
# Default chunk options
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo    = FALSE,
  dpi     = 500
)
```

```{r "packages"}
# tidyverse
library(tidyverse)
library(here)
library(knitr)
library(broom)

# plotting
library(scales)
library(ggrepel)
library(ggtrace)
library(patchwork)
library(cowplot)
library(colorblindr)
library(ggtext)

# analysis
library(Seurat)
library(clustifyr)
library(clustifyrdata)
library(DoubletFinder)
library(M3Drop)
library(CellChat)
library(djvdj)
library(presto)
library(gprofiler2)
library(qs)

library(clusterProfiler)
library(enrichplot)
library(msigdbr)

source(here(params$template_dir, "funs.R"))

chikv_grps <- c("CHIKV-low", "CHIKV-high")
```

```{r "format data"}

# Calculate mean expression for each cell type
so_24 <- qread(here(params$so_dir, "so_24.qs"))

so_chikv <- so_24 %>%
  subset(treatment == "CHIKV")

rm(so_24)

gn_dat <- so_chikv %>%
  Seurat::SplitObject("subtype") %>%
  map(~ {
    .x %>%
      FetchData(rownames(.x)) %>%
      colMeans()
  })

rm(so_chikv)

gn_mat <- gn_dat %>%
  bind_rows() %>%
  as.data.frame()

rownames(gn_mat) <- names(gn_dat)

# Filter genes
# remove all genes where mean expression is 0 for all samples
gn_mat <- gn_mat[, colSums(gn_mat) > 0]

```

```{r "thresholds"}

# Choose a set of soft-thresholding powers
powers <- c(
  c(1:10),
  seq(from = 12, to = 20, by = 2)
)

# Call the network topology analysis function
sft <- pickSoftThreshold(gn_mat, powerVector = powers, verbose = 5)

# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2))
cex1 <- 0.9

# Scale-free topology fit index as a function of the soft-thresholding power
plot(
  sft$fitIndices[,1],
  -sign(sft$fitIndices[,3]) * sft$fitIndices[,2],
  xlab = "Soft Threshold (power)",
  ylab = "Scale Free Topology Model Fit,signed R^2",
  type = "n",
  main = paste("Scale independence")
)

text(
  sft$fitIndices[,1],
  -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
  labels = powers,
  cex = cex1,
  col = "red"
)

# this line corresponds to using an R^2 cut-off of h
abline(h = 0.90, col = "red")

# Mean connectivity as a function of the soft-thresholding power
plot(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  xlab = "Soft Threshold (power)",
  ylab = "Mean Connectivity",
  type = "n",
  main = paste("Mean connectivity")
)

text(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  labels = powers,
  cex = cex1,
  col = "red"
)

```

```{r "network analysis"}

# Identify modules
net <- blockwiseModules(
  gn_mat,
  power = 7,             # Set based on plots shown in previous chunk
  # power = 14,            # Set based on plots shown in previous chunk
  TOMType = "unsigned",
  minModuleSize = 30,
  reassignThreshold = 0,
  mergeCutHeight = 0.25,
  numericLabels = TRUE,
  pamRespectsDendro = FALSE,
  saveTOMs = TRUE,
  saveTOMFileBase = "femaleMouseTOM",
  verbose = 3
)

# GO terms for modules
gn_mods <- split(names(net$colors), net$colors)

go_mods <- gn_mods %>%
  gost(organism = "mmusculus")

go_res <- go_mods$result %>%
  dplyr::filter(
    term_size < 1000, term_size > 10,
    intersection_size > 10
  )

```

```{r "EXAMPLE load data"}

library(tidyverse)
library(WGCNA)

dat_dir <- "~/Downloads/FemaleLiver-Data"

femData <- read_csv(file.path(dat_dir, "LiverFemale3600.csv"))

# Transpose data
datExpr <- femData %>%
  select(substanceBXH, starts_with("F")) %>%
  column_to_rownames("substanceBXH") %>%
  t()

# Filter genes and samples
gsg <- goodSamplesGenes(datExpr, verbose = 3)

gsg$allOK

```

```{r "EXAMPLE setting thresholds"}

# Choose a set of soft-thresholding powers
powers <- c(
  c(1:10),
  seq(from = 12, to = 20, by = 2)
)

# Call the network topology analysis function
sft <- pickSoftThreshold(datExpr, powerVector = powers, verbose = 5)

# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2))
cex1 <- 0.9

# Scale-free topology fit index as a function of the soft-thresholding power
plot(
  sft$fitIndices[,1],
  -sign(sft$fitIndices[,3]) * sft$fitIndices[,2],
  xlab = "Soft Threshold (power)",
  ylab = "Scale Free Topology Model Fit,signed R^2",
  type = "n",
  main = paste("Scale independence")
)

text(
  sft$fitIndices[,1],
  -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
  labels = powers,
  cex = cex1,
  col = "red"
)

# this line corresponds to using an R^2 cut-off of h
abline(h = 0.90, col = "red")

# Mean connectivity as a function of the soft-thresholding power
plot(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  xlab = "Soft Threshold (power)",
  ylab = "Mean Connectivity",
  type = "n",
  main = paste("Mean connectivity")
)

text(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  labels = powers,
  cex = cex1,
  col = "red"
)

```

```{r "EXAMPLE network analysis"}

# Identify modules
net <- blockwiseModules(
  datExpr,
  power = 6,
  TOMType = "unsigned",
  minModuleSize = 30,
  reassignThreshold = 0,
  mergeCutHeight = 0.25,
  numericLabels = TRUE,
  pamRespectsDendro = FALSE,
  saveTOMs = TRUE,
  saveTOMFileBase = "femaleMouseTOM",
  verbose = 3
)

# open a graphics window
sizeGrWindow(12, 9)

# Convert labels to colors for plotting
mergedColors <- labels2colors(net$colors)

# Plot the dendrogram and the module colors underneath
plotDendroAndColors(
  net$dendrograms[[1]],
  mergedColors[net$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05
)

net$MEs %>% dim()

mod_genes <- net$colors

```


