# ==== Config file for running the 10x Cell Ranger pipeline ====================

# Path to the fastq directory, multiple directories can be given.
RAW_DATA:
    - "data/210527_A00405_0403_AHCMYCDSX2"
    - "data/210611_A00405_0409_AHCF55DSX2"

# Path to the output directory.
RESULTS:
    "results/24hpi-enrichment"

# Sample names for gene expression fastqs. If the same libraries were
# sequenced multiple times, just include all the fastq directories in the
# RAW_DATA list and make sure the fastqs from all runs begin with the
# sample name. If gene expression fastqs are not being processed, leave
# this blank.
RNA_SAMPLES:
    - "18M1"
    - "21A1"

